# Generated by Django 5.2.7 on 2025-10-05 18:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('workspaces', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LabelTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('kind', models.CharField(choices=[('PREMADE', 'Premade'), ('CUSTOM', 'Custom')], default='CUSTOM', max_length=10)),
                ('width_mm', models.FloatField(default=50.0)),
                ('height_mm', models.FloatField(default=30.0)),
                ('dpi', models.PositiveIntegerField(default=300)),
                ('schema', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('workspace', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='label_templates', to='workspaces.workspace')),
            ],
        ),
        migrations.CreateModel(
            name='LabelInstance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('data', models.JSONField()),
                ('pdf_path', models.CharField(blank=True, max_length=255)),
                ('png_path', models.CharField(blank=True, max_length=255)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('workspace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='generated_labels', to='workspaces.workspace')),
                ('template', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='generated_instances', to='labels.labeltemplate')),
            ],
        ),
        migrations.CreateModel(
            name='LabelField',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('key', models.CharField(max_length=120)),
                ('field_type', models.CharField(choices=[('TEXT', 'Text'), ('IMAGE', 'Image'), ('CODE', 'Code')], default='TEXT', max_length=8)),
                ('code_format', models.CharField(choices=[('BARCODE', 'Barcode'), ('QRCODE', 'QR Code'), ('NONE', 'None')], default='NONE', max_length=8)),
                ('required', models.BooleanField(default=True)),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('template', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fields', to='labels.labeltemplate')),
            ],
        ),
    ]
